<%-- 
   Copyright 2004 Salesforce.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

--%>

<%@page import="com.sforce.soap.*"%>
<%@taglib prefix="netui-databinding" uri="netui-tags-databinding.tld"%>
<!--Generated by WebLogic Workshop-->
<%@ taglib uri="netui-tags-html.tld" prefix="netui"%>
<%@ taglib uri="netui-tags-template.tld" prefix="netui-template"%>

<style>
<!--table
.style0
   {mso-number-format:General;
   text-align:general;
   vertical-align:bottom;
   white-space:nowrap;
   mso-rotate:0;
   mso-background-source:auto;
   mso-pattern:auto;
   color:windowtext;
   font-size:10.0pt;
   font-weight:400;
   font-style:normal;
   text-decoration:none;
   font-family:Arial;
   mso-generic-font-family:auto;
   mso-font-charset:0;
   border:none;
   mso-protection:locked visible;
   mso-style-name:Normal;
   mso-style-id:0;}
.xl25
   {mso-style-parent:style0;
   border-top:none;
   border-right:none;
   border-bottom:.5pt solid windowtext;
   border-left:none;}
-->
</style>

<netui-template:template templatePage="./../resources/jsp/template.jsp">
	 </blockquote> <netui-template:section name="bodySection"> <blockquote>
                 <netui:anchor action="Logout" style="font-size:10pt;"></netui:anchor>

    <netui:anchor action="GetCustomers">Customers Page</netui:anchor>&nbsp;&nbsp;|&nbsp;&nbsp;
    <netui:anchor action="GetOpportunities">
    Refresh
        <netui:parameter name="accountid" value="{pageFlow.selectedAccount.id}" />
        <netui:parameter name="refresh" value="refresh" />
    </netui:anchor>
    <p class="pagehead" align="left">
    <big>Opportunities for
    <u><netui:anchor action="GetCustomerDetail">
        <netui:parameter name="accountid" value="{pageFlow.selectedAccount.id}" />
    <netui:label value="{pageFlow.selectedAccount.name}" />
    </netui:anchor></u></big></p>
    <netui-databinding:repeater dataSource="{pageFlow.selectedAccount.opportunities}">
        <netui-databinding:repeaterHeader>
            <table width="90%" cellpadding="0" class="tablebody" cellspacing="0" border="0">
                <tr class="tablehead">
                    <td><b> Name </b></td>
                    <td><b> Opportunity Type </b></td>
                    <td><b> Lead Source </b></td>
                    <td><b> Amount </b></td>
                    <td><b> Expected Amount </b></td>
                    <td><b> Close Date </b></td>
                    <td><b> Next Step </b></td>
                </tr>
            </netui-databinding:repeaterHeader>
        <netui-databinding:repeaterItem>
            <tr>
                <td class="xl25">
                <netui:label value="{container.item.name}"></netui:label>
                </td>
                <td class="xl25">
                &nbsp;<netui:label value="{container.item.type}"></netui:label>
                </td>
                <td class="xl25">
                &nbsp;<netui:label value="{container.item.leadSource}"></netui:label>
                </td>
                <td class="xl25">
                &nbsp;<netui:label value="{container.item.amount}"></netui:label>
                </td>
                <td class="xl25">
                &nbsp;<netui:label value="{container.item.expectedAmount}"></netui:label>
                </td>
                <td class="xl25">
                &nbsp;<netui:label value="{container.item.closeDate}"></netui:label>
                </td>
                <td class="xl25">
                &nbsp;<netui:label value="{container.item.nextStep}"></netui:label>
                </td>
            </tr>
        </netui-databinding:repeaterItem>
        <netui-databinding:repeaterFooter> </table> </netui-databinding:repeaterFooter>
    </netui-databinding:repeater>
    </netui-template:section>
</netui-template:template>