<%-- 
   Copyright 2004 Salesforce.com

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

--%>

<%@taglib prefix="netui-databinding" uri="netui-tags-databinding.tld"%>
<!--Generated by WebLogic Workshop-->
<%@ taglib uri="netui-tags-html.tld" prefix="netui"%>
<%@ taglib uri="netui-tags-template.tld" prefix="netui-template"%>

<style>
<!--table
.style0
   {mso-number-format:General;
   text-align:general;
   vertical-align:bottom;
   white-space:nowrap;
   mso-rotate:0;
   mso-background-source:auto;
   mso-pattern:auto;
   color:windowtext;
   font-size:10.0pt;
   font-weight:400;
   font-style:normal;
   text-decoration:none;
   font-family:Arial;
   mso-generic-font-family:auto;
   mso-font-charset:0;
   border:none;
   mso-protection:locked visible;
   mso-style-name:Normal;
   mso-style-id:0;}
.xl25
   {mso-style-parent:style0;
   border-top:none;
   border-right:none;
   border-bottom:.5pt solid windowtext;
   border-left:none;}
-->
</style>

<netui-template:template templatePage="./../resources/jsp/template.jsp">
	<netui-template:section name="bodySection"> &nbsp;&nbsp;&nbsp;
    <blockquote>
	<p class="pagehead" align="center">
	<big>Send Email</p>
	<netui:form action="emailAction">
		<netui:parameter name="accountid" value='<%=request.getParameter("accountid")%>'/>
		<netui:parameter name="customername" value='<%=request.getParameter("customername")%>'/>
		<table width="100%">
            <tr>
                <td>&nbsp;</td>
                <td>
                
                <netui:button tagId="send" value="Send" type="submit"/>&nbsp;&nbsp;&nbsp;
                <netui:button tagId="cancel" type="button" value="Cancel" onClick="javascript: location='GetCustomerDetail.do';"/>
                </td>
            </tr>
            <tr valign="top">
				<td class="rowhead" width="70"><strong>To:</strong></td>
				<td>
				<netui:textBox dataSource="{actionForm.to}" size="90"/>
				</td>
			</tr>
			<tr valign="top">
				<td class="rowhead"><strong>Cc:</strong></td>
				<td>
				<netui:textBox dataSource="{actionForm.cc}" size="90"/>
				</td>
			</tr>
			<tr valign="top">
				<td class="rowhead"><strong>Subject:</strong></td>
				<td>
				<netui:textBox dataSource="{actionForm.subject}" size="90"/>
				</td>
			</tr>
			<tr valign="top">
				<td class="rowhead"><strong>Body:</strong></td>
				<td>
				<netui:textArea dataSource="{actionForm.body}" rows="25" cols="70"/>
				</td>
			</tr>
		</table>
        </blockquote>
		<br/>&nbsp;
		
	</netui:form>
	</netui-template:section>
</netui-template:template>
