import org.apache.beehive.controls.runtime.bean.ControlContainerContext;
import org.apache.xmlbeans.impl.schema.SchemaTypeLoaderImpl;

/**
 * @author <a href="mailto:dan@envoisolutions.com">Dan Diephouse</a>
 */
public class Demo
{
    BookFinder finder;
    
    public Demo() throws Exception
    {
        finder = new BookFinder();
        
        /* This class is generated by Beehive. Normally you wouldn't
         * have to do this, but it just makes the demo a bit easier.
         * The Initializer class takes care of setting up the Amazon
         * client control.
         */ 
        ControlContainerContext context = new ControlContainerContext();
        BookFinderClientInitializer.initialize(context, finder);
    }
  
    public BookFinder getFinder()
    {
        return finder;
    }

    public static void main(String[] args)
        throws Exception
    {
        Demo d = new Demo();
        if (args.length == 0)
            System.out.println("Usage: Demo <ISBN>");
        else
            d.getFinder().findBook(args[0]);
    }
}
